expr: 			term ((MINUS | PLUS) term)*

term:			factor ((MUL | DIV) factor)*

factor: 		((MINUS | PLUS)* ) (INTEGER | LPAREN expr RPAREN)


INTEGER: DIGIT | DIGIT (INTEGER)*
DIGIT: 0|1|2|3|4|5|6|7|8|9
PLUS: +
MINUS: -
MUL: *
DIV: /
LPAREN: (
RPAREN: )
