expr: 			factor ((MINUS | PLUS) (factor | parenthesis))*

factor:			integer ((MUL | DIV) (integer | parenthesis))*

parenthesis: 	OPEN_PAR expr CLOSE_PAR

integer: 		DIGIT | DIGIT (integer)*



DIGIT: 0|1|2|3|4|5|6|7|8|9
PLUS: +
MINUS: -
MUL: *
DIV: /
OPEN_PAR: (
CLOSE_PAR: )
